#!/bin/sh
sbt "project service-net-tests" assembly >&2 &&
rm -rf tests/harness &&
mkdir -p tests/harness &&
cd tests/harness &&
java -cp ../../tests/target/scala-*/*.jar \
  mesosphere.servicenet.tests.TestDocGenerator "$@"
